### PR TITLE
Preliminary Allennlp Support

### LINKED ISSUE #128: Allennlp Support
This was originally discussed in https://github.com/PyTorchLightning/pytorch-lightning/issues/987, and @mikerossgithub tried to add this to PL in https://github.com/PyTorchLightning/pytorch-lightning/pull/1993, but since this depends on allennlp, this issue was transferred to Bolts here. (just for the record)

### PR DESCRIPTION
**Pull request by mikerossgithub**
Moving from here: https://github.com/PyTorchLightning/pytorch-lightning/pull/1993
Fixes #128

Adds an AllenNlp Lightning Module

The module can be initialized from a dictionary of parameters or from an AllenNlp params object. This is a work in progress. Remaining issues:

* I have tested this on my own setup, and it is working. But I have not tested in a distributed environment or built any automated tests
* I am not sure if the vocabulary initialization belongs in the __init__ method or in the prepare_data method. This is probably relevant for distributed training scenarios
* Filtering parameters for AllenNlp is handled in an ugly way via a hard-coded list of parameter prefixes to use for initializing the models
* I am not sure if I am handling the log and progress_bar fields according to best lightning practices
* I do not know where this model belongs in the pytorch-lightning library

Relevant issues:
https://github.com/PyTorchLightning/pytorch-lightning/issues/987

This code is based on @matt-gardner's contribution here:
https://github.com/allenai/allennlp/pull/3860

### CODE REVIEW

**Comment by mikerossgithub** [comment]
I will not be able to finish this in the near future. So I am leaving it here in case someone would lik to continue the work.

**Comment by williamFalcon** [comment]
@mikerossgithub sorry for the delay. now we have the build working again and adding more to the library :)

**Comment by aribornstein** [comment]
I'd be interested in potentially picking this up again to support some of these scenarios (https://demo.allennlp.org/visual-question-answering) what still needs to be verified?

**Comment by yucoian** [comment]
what's going on?

**Pull request closed without merging**
