### PR TITLE
Replace `load_boston` due to Ethical Issues

### PR DESCRIPTION
**Pull request by koaning**
## What does this PR do?

This replaces the `load_boston` dataset with `load_diabetes`. The `load_boston` dataset is up for removal from scikit-learn due to the ethical issues related to the variables in it. https://github.com/scikit-learn/scikit-learn/issues/16155

Fixes # (issue)

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/lightning-bolts/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? [not needed for typos/docs]
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/lightning-bolts/blob/master/CHANGELOG.md)?

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by akihironitta** [comment]
@koaning Hi, thank you for bringing this up and for providing the issue link.

**Comment by akihironitta** [comment]
There are a number of replacements suggested in the linked issue, but as @koaning suggests, `load_diabetes` would be a reasonable replacement because the dataset is small and is included already in scikit-learn.

**Review by edgarriba — APPROVED** [review]
LGTM. Thanks for bringing this up. We are good to go once the tests pass.

**Review by akihironitta — APPROVED** [review]
I believe the failing test is unrelated to the change in this PR. It's being fixed in #633. LGTM!

**Comment by akihironitta** [comment]
Let me check the failing tests

**Pull request merged**
