### PR TITLE
Add type annotations for `plt.models.regression`

### LINKED ISSUE #434: Add type annotations to the codebase
## 🚀 Feature
As static type checker `mypy` was added in #433, we can add type annotations to the codebase.

### PR DESCRIPTION
**Pull request by jeromepatel**
## What does this PR do?

I have added type annotations to the module `plt.models.regression`.  Currently, there are only two files that need to be changed. 
I had one doubt but that is unrelated to this PR, that is, in function `validation_step(self, batch, batch_idx)` the parameter `batch_idx` is not used anywhere in the function but it is a required argument. So, may I suggest it can be changed to optional argument with None option by default. I am not sure but any guidance would be helpful. 
Thank you.

Related to #434 

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/lightning-bolts/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (NA)
- [ ] Did you write any new necessary tests? [not needed for typos/docs] (NA)
- [x] Did you verify new and existing tests pass locally with your changes? 
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/lightning-bolts/blob/master/CHANGELOG.md)? (NA)

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

### CODE REVIEW

**Comment by jeromepatel** [comment]
I am not sure why CodeFactor and other test are failing but any guidance would be helpful.

**Comment by Borda** [comment]
@akihironitta mind have look? :]

**Comment by akihironitta** [comment]
> in function `validation_step(self, batch, batch_idx)` the parameter `batch_idx` is not used anywhere in the function but it is a required argument. So, may I suggest it can be changed to optional argument with None option by default.

@jeromepatel Hi, thank you for your contribution! I wouldn't change it to `batch_idx: Optional[int] = None` because an `int` value is always passed to `batch_idx` anyway.

**Comment by jeromepatel** [comment]
@akihironitta thank you for your reply. The reason seems valid to me. I think there is no need to change it to optional then.   Thanks for reviewing.

**Comment by akihironitta** [comment]
I pushed some commits to this branch directly, but as of 9e36df9, we'll get the following 43 errors from mypy... We might need to rethink if we really need to add type hints to the codebase.

<details>
<summary>mypy errors</summary>

```console
$ mypy -V
mypy 0.800
$ mypy
pl_bolts/utils/semi_supervised.py:98: error: Incompatible return value type (got "Tuple[List[List[Any]], List[List[Any]]]", expected "Tuple[ndarray, ndarray]")  [return-value]
        return final_batches_x, final_batches_y
               ^
pl_bolts/utils/semi_supervised.py:139: error: Incompatible return value type (got "Tuple[List[Any], List[Any]]", expected "Tuple[ndarray, ndarray]")  [return-value]
        return X, Y
               ^
pl_bolts/models/regression/logistic_regression.py:44: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Namespace]" has no attribute "input_dim"  [union-attr]
            self.linear = nn.Linear(in_features=self.hparams.input_dim, out_features=self.hparams.num_classes, bias=bias)
                                                ^
pl_bolts/models/regression/logistic_regression.py:44: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Namespace]" has no attribute "num_classes"  [union-attr]
            self.linear = nn.Linear(in_features=self.hparams.input_dim, out_features=self.hparams.num_classes, bias=bias)
                                                                                     ^
pl_bolts/models/regression/logistic_regression.py:46: error: Signature of "forward" incompatible with supertype "LightningModule"  [override]
        def forward(self, x: Tensor) -> Tensor:
        ^
pl_bolts/models/regression/logistic_regression.py:51: error: Signature of "training_step" incompatible with supertype "LightningModule"  [override]
        def training_step(self, batch: Tuple[Tensor, Tensor], batch_idx: int) -> Dict[str, Tensor]:
        ^
pl_bolts/models/regression/logistic_regression.py:63: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Namespace]" has no attribute "l1_strength"  [union-attr]
            if self.hparams.l1_strength > 0:
               ^
pl_bolts/models/regression/logistic_regression.py:65: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Namespace]" has no attribute "l1_strength"  [union-attr]
                loss += self.hparams.l1_strength * l1_reg
                        ^
pl_bolts/models/regression/logistic_regression.py:68: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Namespace]" has no attribute "l2_strength"  [union-attr]
            if self.hparams.l2_strength > 0:
               ^
pl_bolts/models/regression/logistic_regression.py:70: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Namespace]" has no attribute "l2_strength"  [union-attr]
                loss += self.hparams.l2_strength * l2_reg
                        ^
pl_bolts/models/regression/logistic_regression.py:76: error: Dict entry 1 has incompatible type "str": "Dict[str, Tensor]"; expected "str": "Tensor"  [dict-item]
            return {'loss': loss, 'log': tensorboard_logs, 'progress_bar': progress_bar_metrics}
                                  ^
pl_bolts/models/regression/logistic_regression.py:76: error: Dict entry 2 has incompatible type "str": "Dict[str, Tensor]"; expected "str": "Tensor"  [dict-item]
            return {'loss': loss, 'log': tensorboard_logs, 'progress_bar': progress_bar_metrics}
                                                           ^
pl_bolts/models/regression/logistic_regression.py:78: error: Signature of "validation_step" incompatible with supertype "LightningModule"  [override]
        def validation_step(self, batch: Tuple[Tensor, Tensor], batch_idx: int) -> Dict[str, Tensor]:
        ^
pl_bolts/models/regression/logistic_regression.py:85: error: Return type "Dict[str, Tensor]" of "validation_epoch_end" incompatible with return type "None" in supertype "LightningModule" 
[override]
        def validation_epoch_end(self, outputs: List[Dict[str, Tensor]]) -> Dict[str, Tensor]:
        ^
pl_bolts/models/regression/logistic_regression.py:90: error: Dict entry 1 has incompatible type "str": "Dict[str, Tensor]"; expected "str": "Tensor"  [dict-item]
            return {'val_loss': val_loss, 'log': tensorboard_logs, 'progress_bar': progress_bar_metrics}
                                          ^
pl_bolts/models/regression/logistic_regression.py:90: error: Dict entry 2 has incompatible type "str": "Dict[str, Tensor]"; expected "str": "Tensor"  [dict-item]
            return {'val_loss': val_loss, 'log': tensorboard_logs, 'progress_bar': progress_bar_metrics}
                                                                   ^
pl_bolts/models/regression/logistic_regression.py:92: error: Signature of "test_step" incompatible with supertype "LightningModule"  [override]
        def test_step(self, batch: Tuple[Tensor, Tensor], batch_idx: int) -> Dict[str, Tensor]:
        ^
pl_bolts/models/regression/logistic_regression.py:93: error: Cannot resolve name "x" (possible cyclic definition)  [misc]
            x = x.view(x.size(0), -1)
                ^
pl_bolts/models/regression/logistic_regression.py:95: error: Name 'y' is not defined  [name-defined]
            acc = accuracy(y_hat, y)
                                  ^
pl_bolts/models/regression/logistic_regression.py:96: error: Name 'y' is not defined  [name-defined]
            return {'test_loss': F.cross_entropy(y_hat, y), 'acc': acc}
                                                        ^
pl_bolts/models/regression/logistic_regression.py:98: error: Return type "Dict[str, Tensor]" of "test_epoch_end" incompatible with return type "None" in supertype "LightningModule"  [override]
        def test_epoch_end(self, outputs: List[Dict[str, Tensor]]) -> Dict[str, Tensor]:
        ^
pl_bolts/models/regression/logistic_regression.py:103: error: Dict entry 1 has incompatible type "str": "Dict[str, Tensor]"; expected "str": "Tensor"  [dict-item]
            return {'test_loss': test_loss, 'log': tensorboard_logs, 'progress_bar': progress_bar_metrics}
                                            ^
pl_bolts/models/regression/logistic_regression.py:103: error: Dict entry 2 has incompatible type "str": "Dict[str, Tensor]"; expected "str": "Tensor"  [dict-item]
            return {'test_loss': test_loss, 'log': tensorboard_logs, 'progress_bar': progress_bar_metrics}
                                                                     ^
pl_bolts/models/regression/logistic_regression.py:106: error: Unexpected keyword argument "lr" for "Optimizer"  [call-arg]
            return self.optimizer(self.parameters(), lr=self.hparams.learning_rate)
                   ^
pl_bolts/models/regression/logistic_regression.py:106: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Namespace]" has no attribute "learning_rate"  [union-attr]
            return self.optimizer(self.parameters(), lr=self.hparams.learning_rate)
                                                        ^
pl_bolts/models/regression/logistic_regression.py:145: error: Cannot instantiate abstract class 'SklearnDataModule' with abstract attributes 'prepare_data', 'setup' and 'transfer_batch_to_device'
 [abstract]
        loaders = SklearnDataModule(X, y, batch_size=args.batch_size, num_workers=0)
                  ^
pl_bolts/models/regression/linear_regression.py:43: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Namespace]" has no attribute "input_dim"  [union-attr]
            self.linear = nn.Linear(in_features=self.hparams.input_dim, out_features=self.hparams.output_dim, bias=bias)
                                                ^
pl_bolts/models/regression/linear_regression.py:43: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Namespace]" has no attribute "output_dim"  [union-attr]
            self.linear = nn.Linear(in_features=self.hparams.input_dim, out_features=self.hparams.output_dim, bias=bias)
                                                                                     ^
pl_bolts/models/regression/linear_regression.py:45: error: Signature of "forward" incompatible with supertype "LightningModule"  [override]
        def forward(self, x: Tensor) -> Tensor:
        ^
pl_bolts/models/regression/linear_regression.py:49: error: Signature of "training_step" incompatible with supertype "LightningModule"  [override]
        def training_step(self, batch: Tuple[Tensor, Tensor], batch_idx: int) -> Dict[str, Tensor]:
        ^
pl_bolts/models/regression/linear_regression.py:60: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Namespace]" has no attribute "l1_strength"  [union-attr]
            if self.hparams.l1_strength > 0:
               ^
pl_bolts/models/regression/linear_regression.py:62: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Namespace]" has no attribute "l1_strength"  [union-attr]
                loss += self.hparams.l1_strength * l1_reg
                        ^
pl_bolts/models/regression/linear_regression.py:65: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Namespace]" has no attribute "l2_strength"  [union-attr]
            if self.hparams.l2_strength > 0:
               ^
pl_bolts/models/regression/linear_regression.py:67: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Namespace]" has no attribute "l2_strength"  [union-attr]
                loss += self.hparams.l2_strength * l2_reg
                        ^
pl_bolts/models/regression/linear_regression.py:73: error: Dict entry 1 has incompatible type "str": "Dict[str, Tensor]"; expected "str": "Tensor"  [dict-item]
            return {'loss': loss, 'log': tensorboard_logs, 'progress_bar': progress_bar_metrics}
                                  ^
pl_bolts/models/regression/linear_regression.py:73: error: Dict entry 2 has incompatible type "str": "Dict[str, Tensor]"; expected "str": "Tensor"  [dict-item]
            return {'loss': loss, 'log': tensorboard_logs, 'progress_bar': progress_bar_metrics}
                                                           ^
pl_bolts/models/regression/linear_regression.py:75: error: Signature of "validation_step" incompatible with supertype "LightningModule"  [override]
        def validation_step(self, batch: Tuple[Tensor, Tensor], batch_idx: int) -> Dict[str, Tensor]:
        ^
pl_bolts/models/regression/linear_regression.py:81: error: Return type "Dict[str, Tensor]" of "validation_epoch_end" incompatible with return type "None" in supertype "LightningModule" 
[override]
        def validation_epoch_end(self, outputs: List[Dict[str, Tensor]]) -> Dict[str, Tensor]:
        ^
pl_bolts/models/regression/linear_regression.py:85: error: Dict entry 1 has incompatible type "str": "Dict[str, Tensor]"; expected "str": "Tensor"  [dict-item]
            return {'val_loss': val_loss, 'log': tensorboard_logs, 'progress_bar': progress_bar_metrics}
                                          ^
pl_bolts/models/regression/linear_regression.py:85: error: Dict entry 2 has incompatible type "str": "Dict[str, Tensor]"; expected "str": "Tensor"  [dict-item]
            return {'val_loss': val_loss, 'log': tensorboard_logs, 'progress_bar': progress_bar_metrics}
                                                                   ^
pl_bolts/models/regression/linear_regression.py:87: error: Signature of "test_step" incompatible with supertype "LightningModule"  [override]
        def test_step(self, batch: Tuple[Tensor, Tensor], batch_idx: int) -> Dict[str, Tensor]:
        ^
pl_bolts/models/regression/linear_regression.py:92: error: Return type "Dict[str, Tensor]" of "test_epoch_end" incompatible with return type "None" in supertype "LightningModule"  [override]
        def test_epoch_end(self, outputs: List[Dict[str, Tensor]]) -> Dict[str, Tensor]:
        ^
pl_bolts/models/regression/linear_regression.py:96: error: Dict entry 1 has incompatible type "str": "Dict[str, Tensor]"; expected "str": "Tensor"  [dict-item]
            return {'test_loss': test_loss, 'log': tensorboard_logs, 'progress_bar': progress_bar_metrics}
                                            ^
pl_bolts/models/regression/linear_regression.py:96: error: Dict entry 2 has incompatible type "str": "Dict[str, Tensor]"; expected "str": "Tensor"  [dict-item]
            return {'test_loss': test_loss, 'log': tensorboard_logs, 'progress_bar': progress_bar_metrics}
                                                                     ^
pl_bolts/models/regression/linear_regression.py:99: error: Unexpected keyword argument "lr" for "Optimizer"  [call-arg]
            return self.optimizer(self.parameters(), lr=self.hparams.learning_rate)
                   ^
pl_bolts/models/regression/linear_regression.py:99: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Namespace]" has no attribute "learning_rate"  [union-attr]
            return self.optimizer(self.parameters(), lr=self.hparams.learning_rate)
                                                        ^
pl_bolts/models/regression/linear_regression.py:138: error: Cannot instantiate abstract class 'SklearnDataModule' with abstract attributes 'prepare_data', 'setup' and 'transfer_batch_to_device' 
[abstract]
        loaders = SklearnDataModule(X, y, batch_size=args.batch_size)
                  ^
Found 47 errors in 3 files (checked 197 source files)
```

</details>

**Comment by jeromepatel** [comment]
@akihironitta  so, should we revisit this issue after solving the error or maybe close this PR as of now and work on more important issues? Thank you for your reply.

**Review by Borda — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
LGTM !

**Comment by abhayraw1** [comment]
This change is causing tests to fail in master. Please check!

https://github.com/PyTorchLightning/lightning-bolts/pull/595/commits/3bf65da4d611445a9b09399f7bcee68510c8ca13#diff-81b21ad681f00e8e80279aaf4d5e2c3a304b5a587b79850cff8d4472147f7f0aL92

**Pull request merged**
